# Generated by Django 2.1 on 2019-03-01 04:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20190301_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='test',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 1, 12, 36, 0, 887940)),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 1, 12, 36, 0, 883890)),
        ),
        migrations.AlterField(
            model_name='review',
            name='date_reviewed',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 1, 12, 36, 0, 887940)),
        ),
        migrations.AlterField(
            model_name='step',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 1, 12, 36, 0, 887940)),
        ),
    ]
